Im pretty tired
dkess/irc-multibouncer pull request #1
Opened 2017-11-18 13:34 UTC by kkuehler

One other thing I forgot to mention in my commit message is for private message, join channel, etc., you already check if the nick is part of the session, so we only have to validate it once when it's registered.

2017-11-18 19:09 UTC, dkess commented
Uhh I installed iPython for debugging purposes, that might have caused Twisted to show up.

2017-11-18 19:44 UTC, dkess requested changes
Thanks for the PR. Lots of good stuff here (style fixes are especially welcome) but there are definitely some new bugs. Also I'll try to document stuff more so the code makes more sense.

2017-11-18 19:44 UTC, dkess commented on server.py
> -    # TODO: not strict enough
This TODO should stay, since this still isn't quite RFC2812 (for example, you're not allowed to start a nick with numbers).

2017-11-18 19:44 UTC, dkess commented on server.py
> +        if not self._target_state:
Looks like you misunderstood this if statement: we want to join the channel if target state is true, and we want to part the channel if target state is false.

2017-11-18 19:44 UTC, dkess commented on server.py
> +            if strip_nick(spl[0][1:]) == nick:
Good catch. There should probably be a better system for parsing IRC lines.

2017-11-18 19:44 UTC, dkess commented on server.py
> +async def channel_join_part(request):
I guess these could be combined, though checking `request.path` twice worries me. There's probably a better way to organize this though.

2017-11-18 19:44 UTC, dkess commented on server.py
> -        self.onStateChange()
This line is important, not sure why you removed it.

2017-11-18 19:44 UTC, dkess commented on server.py
> +        sd.channels[channel].changeTargetState(False)
This should be True.

2017-11-18 19:45 UTC, dkess commented
Just read what you said about "circular calls." That is 100% intentional, so don't try to get rid of it.

2017-11-23 05:33 UTC, kkuehler commented
bump.

2017-11-23 05:34 UTC, dkess commented
Sorry for the delay, I'm busy tomorrow but on Friday I'll look at this

2017-11-24 20:27 UTC, dkess approved these changes

2017-11-24 20:27 UTC, merged